#!/bin/env ruby
# encoding: utf-8
class Constants

	PROVINCE = [
		"Alberta", 
		"British Columbia", 
		"Manitoba", 
		"New Brunswick", 
		"Newfoundland and Labrador",
		"Northwest Territories",
		"Nova Scotia",
		"Nunavut",
		"Ontario",
		"Prince Edward Island",
		"Quebec",
		"Saskatchewan", 
		"Yukon"
	]
  	

  	LOCATION = {
		'Alberta' => [
			"Airdrie",
			"Brooks",
			"Calgary",
			"Camrose",
			"Cold Lake",
			"Edmonton",
			"Fort Saskatchewan",
			"Grande Prairie",
			"Lacombe",
			"Leduc",
			"Lethbridge",
			"Lloydminster",
			"Medicine Hat",
			"Red Deer",
			"Spruce Grove",
			"St. Albert",
			"Wetaskiwin"
			],
		'British Columbia' => [
			"Abbotsford",
			"Armstrong",
			"Burnaby",
			"Campbell River",
			"Castlegar",
			"Chilliwack",
			"Colwood",
			"Coquitlam",
			"Courtenay",
			"Cranbrook",
			"Dawson Creek",
			"Duncan",
			"Enderby",
			"Fernie",
			"Fort St. John",
			"Grand Forks",
			"Greenwood",
			"Kamloops",
			"Kelowna",
			"Kimberley",
			"Langford",
			"Langley",
			"Merritt",
			"Nanaimo",
			"Nelson",
			"New Westminster",
			"North Vancouver",
			"Parksville",
			"Penticton",
			"Pitt Meadows",
			"Port Alberni",
			"Port Coquitlam",
			"Port Moody",
			"Powell River",
			"Prince George",
			"Prince Rupert",
			"Quesnel",
			"Revelstoke",
			"Richmond",
			"Rossland",
			"Salmon Arm",
			"Surrey",
			"Terrace",
			"Trail",
			"Vancouver",
			"Vernon",
			"Victoria",
			"White Rock",
			"Williams Lake"
			],
		'Manitoba' => [
			"Brandon",
			"Dauphin",
			"Flin Flon",
			"Morden",
			"Portage la Prairie",
			"Selkirk",
			"Steinbach",
			"Thompson",
			"Winkler",
			"Winnipeg"
			],
		'New Brunswick' => [
			"Bathurst",
			"Campbellton",
			"Dieppe",
			"Edmundston",
			"Fredericton",
			"Miramichi",
			"Moncton",
			"Saint John"
			],
		'Newfoundland and Labrador' => [
			"Corner Brook",
			"Mount Pearl",
			"St. John's"
			],
		'Northwest Territories' => [
			"Yellowknife"
			],
		'Nova Scotia' => [
			"Halifax",
			"Sydney",
			"Dartmouth"
			],
		'Nunavut' => [
			"Iqaluit"
			],
		'Ontario' => [
			"Barrie",
			"Belleville",
			"Brampton",
			"Brant",
			"Brantford",
			"Brockville",
			"Burlington",
			"Cambridge",
			"Chatham-Kent",
			"Clarence-Rockland",
			"Cornwall",
			"Dryden",
			"Elliot Lake",
			"Greater Sudbury",
			"Guelph",
			"Haldimand County",
			"Hamilton",
			"Kawartha Lakes",
			"Kenora",
			"Kingston",
			"Kitchener",
			"London",
			"Markham",
			"Mississauga",
			"Niagara Falls",
			"Norfolk County",
			"North Bay",
			"Orillia",
			"Oshawa",
			"Ottawa",
			"Owen Sound",
			"Pembroke",
			"Peterborough",
			"Pickering",
			"Prince Edward County",
			"Port Colborne",
			"Quinte West",
			"Sarnia",
			"Sault Ste. Marie",
			"St. Catharines",
			"St. Thomas",
			"Stratford",
			"Temiskaming Shores",
			"Thorold",
			"Thunder Bay",
			"Timmins",
			"Toronto",
			"Vaughan",
			"Waterloo",
			"Welland",
			"Windsor",
			"Woodstock"
			],
		'Prince Edward Island' => [
			"Charlottetown",
			"Summerside"
			],
		'Quebec' => [
			"Acton Vale",
			"Alma",
			"Amos",
			"Amqui",
			"Asbestos",
			"Baie-Comeau",
			"Baie-d'Urfé",
			"Baie-Saint-Paul",
			"Barkmere",
			"Beaconsfield",
			"Beauceville",
			"Beauharnois",
			"Beaupre",
			"Bedford",
			"Belleterre",
			"Beloeil",
			"Berthierville",
			"Blainville",
			"Bois-des-Filion",
			"Boisbriand",
			"Bonaventure",
			"Boucherville",
			"Brome Lake",
			"Bromont",
			"Brossard",
			"Brownsburg-Chatham",
			"Becancour",
			"Candiac",
			"Cap-Chat",
			"Cap-Sante",
			"Carignan",
			"Carleton-sur-Mer",
			"Causapscal",
			"Chambly",
			"Chandler",
			"Chapais",
			"Charlemagne",
			"Chateau-Richer",
			"Chateauguay",
			"Chibougamau",
			"Clermont",
			"Coaticook",
			"Contrecoeur",
			"Cookshire-Eaton",
			"Coteau-du-Lac",
			"Cowansville",
			"Cote Saint-Luc",
			"Danville",
			"Daveluyville",
			"Degelis",
			"Delson",
			"Desbiens",
			"Deux-Montagnes",
			"Disraeli",
			"Dolbeau-Mistassini",
			"Dollard-des-Ormeaux",
			"Donnacona",
			"Dorval",
			"Drummondville",
			"Dunham",
			"Duparquet",
			"East Angus",
			"Esterel",
			"Farnham",
			"Fermont",
			"Forestville",
			"Fossambault-sur-le-Lac",
			"Gaspe",
			"Gatineau",
			"Gracefield",
			"Granby",
			"Grande-Riviere",
			"Hampstead",
			"Hudson",
			"Huntingdon",
			"Joliette",
			"Kingsey Falls",
			"Kirkland",
			"L'Ancienne-Lorette",
			"L'Assomption",
			"L'Épiphanie",
			"L'Île-Cadieux",
			"L'Île-Dorval",
			"L'Île-Perrot",
			"La Malbaie",
			"La Pocatière",
			"La Prairie",
			"La Sarre",
			"La Tuque",
			"Lac-Delage",
			"Lac-Mégantic",
			"Lac-Saint-Joseph",
			"Lac-Sergent",
			"Lachute",
			"Laval",
			"Lavaltrie",
			"Lebel-sur-Quévillon",
			"Léry",
			"Lévis",
			"Longueuil",
			"Lorraine",
			"Louiseville",
			"Macamic",
			"Magog",
			"Malartic",
			"Maniwaki",
			"Marieville",
			"Mascouche",
			"Matagami",
			"Matane",
			"Mercier",
			"Métabetchouan–Lac-à-la-Croix",
			"Métis-sur-Mer",
			"Mirabel",
			"Mont-Joli",
			"Mont-Laurier",
			"Mont-Saint-Hilaire",
			"Mont-Tremblant",
			"Montmagny",
			"Montreal",
			"Montreal West",
			"Montréal-Est",
			"Mount Royal",
			"Murdochville",
			"Neuville",
			"New Richmond",
			"Nicolet",
			"Normandin",
			"Notre-Dame-de-l'Île-Perrot",
			"Notre-Dame-des-Prairies",
			"Otterburn Park",
			"Paspébiac",
			"Percé",
			"Pincourt",
			"Plessisville",
			"Pohénégamook",
			"Pointe-Claire",
			"Pont-Rouge",
			"Port-Cartier",
			"Portneuf",
			"Princeville",
			"Prévost",
			"Quebec City",
			"Repentigny",
			"Richelieu",
			"Richmond",
			"Rimouski",
			"Rivière-du-Loup",
			"Rivière-Rouge",
			"Roberval",
			"Rosemère",
			"Rouyn-Noranda",
			"Saguenay",
			"Sainte-Adèle",
			"Sainte-Agathe-des-Monts",
			"Sainte-Anne-de-Beaupré",
			"Sainte-Anne-de-Bellevue",
			"Sainte-Anne-des-Monts",
			"Sainte-Anne-des-Plaines",
			"Saint-Augustin-de-Desmaures",
			"Saint-Basile",
			"Saint-Basile-le-Grand",
			"Saint-Bruno-de-Montarville",
			"Sainte-Catherine",
			"Sainte-Catherine-de-la-Jacques-Cartier",
			"Saint-Césaire",
			"Saint-Colomban",
			"Saint-Constant",
			"Saint-Eustache",
			"Saint-Félicien",
			"Saint-Gabriel",
			"Saint-Georges",
			"Saint-Hyacinthe",
			"Saint-Jean-sur-Richelieu",
			"Saint-Jérôme",
			"Saint-Joseph-de-Beauce",
			"Saint-Joseph-de-Sorel",
			"Sainte-Julie",
			"Saint-Lambert",
			"Saint-Lazare",
			"Saint-Lin–Laurentides",
			"Saint-Marc-des-Carrières",
			"Sainte-Marguerite-du-Lac-Masson",
			"Sainte-Marie",
			"Sainte-Marthe-sur-le-Lac",
			"Saint-Ours",
			"Saint-Pamphile",
			"Saint-Pascal",
			"Saint-Pie",
			"Saint-Raymond",
			"Saint-Rémi",
			"Saint-Sauveur",
			"Sainte-Thérèse",
			"Saint-Tite",
			"Salaberry-de-Valleyfield",
			"Schefferville",
			"Scotstown",
			"Senneterre",
			"Sept-Îles",
			"Shawinigan",
			"Sherbrooke",
			"Sorel-Tracy",
			"Stanstead",
			"Sutton",
			"Témiscaming",
			"Témiscouata-sur-le-Lac",
			"Terrebonne",
			"Thetford Mines",
			"Thurso",
			"Trois-Pistoles",
			"Trois-Rivières",
			"Val-d'Or",
			"Valcourt",
			"Varennes",
			"Vaudreuil-Dorion",
			"Victoriaville",
			"Ville-Marie",
			"Warwick",
			"Waterloo",
			"Waterville",
			"Westmount",
			"Windsor"
			],
		'Saskatchewan' => [
			"Estevan",
			"Flin Flon",
			"Humboldt",
			"Lloydminster",
			"Martensville",
			"Meadow Lake",
			"Melfort",
			"Melville",
			"Moose Jaw",
			"North Battleford",
			"Prince Albert",
			"Regina",
			"Saskatoon",
			"Swift Current",
			"Warman",
			"Weyburn",
			"Yorkton"
			],
		'Yukon' => [
			"Whitehorse"
		]
	}

end